# Generated by Django 4.2.9 on 2024-05-12 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0002_schoolstaff_alter_leave_status'),
        ('students', '0002_student_date_of_enrollment_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
