# Generated by Django 4.2.9 on 2024-05-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_schoolstaff_alter_leave_status'),
        ('students', '0003_student_classes_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='clasfee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='classname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.class'),
        ),
    ]
