# Generated by Django 4.2.9 on 2024-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentfee_clasfee_studentfee_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfee',
            old_name='clasfee',
            new_name='classfee',
        ),
    ]
