# Generated by Django 4.2.9 on 2024-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_amount_studentfee_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
    ]
