# Generated by Django 4.2.9 on 2024-05-12 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0002_schoolstaff_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
