# Generated by Django 4.2.9 on 2024-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_class_classteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='teachers.class'),
        ),
    ]
