# Generated by Django 4.2.9 on 2024-05-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_classes_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
